#include <iostream>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>

using namespace std;

int main() 
{
 
	int x, y;
	cout << "X: " << endl;
	cin >> x;
	cout << "Y: " << endl;
	cin >> y;

	int a{12};
	int b{1};
	int c{34};
	int chisl1{x + y};
	int chisl2{x * y - a};
	int znam1{x + b};
	int znam2{c + x};

	cout << "Solution: " << endl;
	cout << chisl1 << "/" << znam1 << " - " << chisl2 << "/" << znam2 << " = " << chisl1 * znam2 << "/" << znam1 * znam2 << " - " << chisl2 * znam1 << "/" << znam2 * znam1 << " = " << endl;
	cout << ((chisl1 * znam2 - chisl2 * znam1)) << "/" << (znam1 * znam2) << " = " << round((chisl1 * znam2 - chisl2 * znam1)) / (znam1 * znam2) << endl;

	return 0;
}
